config/routes.rb
Rails.application.routes.draw do
  # resources :stories, only: [:index]
  resources :stories, only: [:index] do
    get 'page/:page', action: :index, on: :collection
  end
  root "stories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  paginates_per 30
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all.page(params[:page]).per(30)

    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hacker Stories</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="https://news.ycombinator.com/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>

    <header>
      <div class="">

        <%= link_to image_tag("https://news.ycombinator.com/y18.gif", height: '18', width: '18', alt: "Hacker Stories", class: "menu_icon"), root_path %>

        <nav>
          <%= link_to stories_path do %>
          <h1>Hacker Stories</h1>
          <% end %>
          <ul>
            <li><%= link_to "new", "https://news.ycombinator.com/newest" %></li> |
            <li><%= link_to "comments", "https://news.ycombinator.com/newcomments" %></li> |
            <li><%= link_to "show", "https://news.ycombinator.com/show" %></li> |
            <li><%= link_to "ask", "https://news.ycombinator.com/ask" %></li> |
            <li><%= link_to "jobs", "https://news.ycombinator.com/jobs" %></li> |
            <li><%= link_to "submit", "https://news.ycombinator.com/submit" %></li>
          </ul>
        </nav>
      </div>
      <div class="login">
        <%= link_to "login", "https://news.ycombinator.com/login?goto=news" %>
      </div>
    </header>
    <main>
      <%= yield %>
      <footer>
        <hr>
        <ul>
          <li><%= link_to "Guidelines", "https://news.ycombinator.com/newsguidelines.html" %></li> |
          <li><%= link_to "FAQ", "https://news.ycombinator.com/newsfaq.html" %></li> |
          <li><%= link_to "Support", "mailto:hn@ycombinator.com" %></li> |
          <li><%= link_to "API", "https://github.com/HackerNews/API" %></li> |
          <li><%= link_to "Security", "https://news.ycombinator.com/security.html" %></li> |
          <li><%= link_to "Lists", "https://news.ycombinator.com/lists" %></li> |
          <li><%= link_to "Bookmarklet", "https://news.ycombinator.com/bookmarklet.html" %></li> |
          <li><%= link_to "Legal", "http://www.ycombinator.com/legal/" %></li> |
          <li><%= link_to "Apply to YC", "https://www.ycombinator.com/apply" %></li> |
          <li><%= link_to "Contact", "mailto:hn@ycombinator.com" %></li>
        </ul>
        <div class="search">
          Search:
          <%= text_field_tag 'search' %>
        </div>
      </footer>
    </main>
  </body>
</html>

app/views/stories/_story.html.erb
<li>
<div class="wrapper">
  <%= link_to "https://news.ycombinator.com/vote?id=#{story.id}&how=up&goto=news" do %>
    <div class="upvote" title="upvote"></div>
  <% end %>

  <article>
    <!-- title -->
    <% if story.url %>
      <%= link_to story.title, story.url, class: "title" %>
    <% else %>
      <%= link_to story.title, "https://news.ycombinator.com/item?id=#{story.id}", class: "title" %>
    <% end %>

    <!-- from site -->
    <% if story.url %>
      <span class="sm-text">
      (<%= link_to story.site, "https://news.ycombinator.com/from?site=#{story.site}" %>)
      </span>
    <% end %>
    <br>
    <!-- points -->
    <span class="sm-text line2">
      <% if story.points %>
        <%= story.points %> points
      <% end %>
      <!-- author -->
      <% if story.author %>
        by <%= link_to story.author, "https://news.ycombinator.com/user?id=#{story.author}" %>
      <% end %>
      <!-- time -->
      <%= link_to "https://news.ycombinator.com/item?id=#{story.id}" do %>
        <%= story.time %>
      <% end %>
      <!-- hide link -->
      | <%= link_to "hide", "https://news.ycombinator.com/hide?id=#{story.id}&goto=news"%> |
      <!-- comments -->
      <% if story.comments && (story.comments > 1) %>

        <%= link_to "https://news.ycombinator.com/item?id=#{story[:id]}" do %>
          <%= story.comments %> comments
        <% end %>
      <% elsif story.comments && (story.comments == 1) %>

        <%= link_to "https://news.ycombinator.com/item?id=#{story[:id]}" do %>
          <%= story.comments %> comment
        <% end %>
      <% elsif story.comments && story.comments <= 0 %>
        <%= link_to "discuss", "https://news.ycombinator.com/item?id=#{story.id}" %>
      <% end %>
    </span>
  </article>
</div>
</li>

app/views/stories/index.html.erb
<ol id="content">
    <%= render(partial: 'story', collection: @stories) %>
</ol>

<% unless @stories.current_page == @stories.total_pages %>
  <p id="view-more">
    <%= link_to('View More', url_for(page: @stories.current_page + 1), remote: true) %>
  </p>
<% end %>

app/views/stories/index.js.erb
  content = document.querySelector('#content'),
  main = document.querySelector('main'),
  viewmore = document.querySelector('#view-more'),
  viewlink = document.querySelector('#view-more a'),
  more = document.createElement('div')

more.innerHTML = "<%=j render(partial: 'story', collection: @stories, format: 'html') %>"
content.appendChild(more)
console.log("Added")

<% if @stories.current_page == @stories.total_pages %>
  main.removeChild(viewmore)
<% else %>
  viewlink.href = '<%= url_for(page: @stories.current_page + 1) %>'
<% end %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @story.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @story.url %>
</p>

<p>
  <strong>Site:</strong>
  <%= @story.site %>
</p>

<p>
  <strong>Points:</strong>
  <%= @story.points %>
</p>

<p>
  <strong>Author:</strong>
  <%= @story.author %>
</p>

<p>
  <strong>Time:</strong>
  <%= @story.time %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @story.comments %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>